### ISSUE TITLE
Ordenador y Movil -- Resultados de las busquedas

### ISSUE THREAD

**Issue by Keyblader** [Keyblader/Azeroth#4]
Pasa tanto cuando buscamos un bar como cuando buscamos una tapa:
- Si existen coincidencias
![busqueda 1](https://cloud.githubusercontent.com/assets/12157698/7676664/20aea020-fd46-11e4-9e8e-ac136c1238d3.png)
- Si no existen coincidencias
![busqueda 2](https://cloud.githubusercontent.com/assets/12157698/7676671/2b33a612-fd46-11e4-939c-917782d9b19c.png)

**Comment by t4l10n** [comment]
No aparece bien la imagen

**Comment by t4l10n** [comment]
Solicionado, faltaba añadir el css

**Comment by t4l10n** [comment]
Vale, el fallo es que no sale el menú completo
