### ISSUE TITLE
Movil y PC -- Error en la geolocalización

### ISSUE THREAD

**Issue by Keyblader** [Keyblader/Azeroth#6]
A la hora de mostrar los detalles de un bar, la posición que me devuelve es diferente cuando accedo desde el movil y cuando accedo desde el PC. Cuando accedo desde el movil CREO que da bien la posición, sin embargo, cuando accedo desde el ordenador me devuelve mi posición actual. Os paso un par de imagenes donde se muestra esto (ambas son de detalle del mismo bar):

- Ordenador (estaba en rabanales cuando hice el pantallazo)
![error localizacion](https://cloud.githubusercontent.com/assets/12157698/7677351/8b6c3486-fd4b-11e4-8926-92ed5fdcd499.png)

- Movil (tambien lo subi estando en rabanales) --> las coordenadas las meti aleatoriamente cuando cree el bar asi que no estoy completamente seguro de que funcione bien del todo ya que no se exactamente que ubicación me deberia de dar
![screenshot_2015-05-18-10-44-23](https://cloud.githubusercontent.com/assets/12157698/7677434/48eb5a46-fd4c-11e4-8ddd-32f82c5d6ea6.png)

**Comment by adiaza** [comment]
Pablo, el problema de esto es que en la plantilla "detalleBar.html" tengo puesto el script que coge la ubicación de la base de datos, pero esta plantilla hereda de "base.html" en la que insertas el script "script.js", entonces primero ejecuta el script que hay en la plantilla "detalleBar.html" y dibuja el mapa bien, pero justo después ejecuta el "script.js" y pisa el mapa que ha dibujado antes, mostrando la ubicación actual.

He pensado que la solución sería quitar del "base.html" el "script.js" y añadirlo directamente en "anyadirBar.html". Ahora mismo lo que he hecho es comentarlo en el "base.html" y añadirlo en "anyadirBar.html" pero si ves otra forma de hacerlo modifícalo.

**Comment by adiaza** [comment]
Pablo, al final he tenido que volver a poner el "script.js" en el "base.html" por que dejaba de funcionar el menú lateral, echale un vistazo cuando puedas, pero el problema es ese que he comentado antes.
